### ISSUE TITLE
RIGHT CLICK - CRASH AND CLOSE

### ISSUE THREAD

**Issue by etunni** [Mark2Mark/script-deck-plugin#2]
Hi Mark,
On rigth click G3 latest on MacOS 10.15 crash and close. See attached report.
Cheers, Edu
[SCRIPT-DESK-report-20nov23.rtf.zip](https://github.com/Mark2Mark/script-deck-plugin/files/13418241/SCRIPT-DESK-report-20nov23.rtf.zip)

**Comment by Mark2Mark** [comment]
Hi Edu,

Thanks for reporting. Your Mac OS is too old to be able to render the icons.

I will push an update in a bit, that disables the Icon feature for Mac versions older than 11.0

Sorry about that.

**Comment by Mark2Mark** [comment]
Hi @etunni, is this solved for you now?
Thanks for your patience.

**Comment by etunni** [comment]
Don't work >> Right click >> crash and close.
No problem I can wait.

[CRASH REPORT 29-NOV-2023.rtf.zip](https://github.com/Mark2Mark/script-deck-plugin/files/13505407/CRASH.REPORT.29-NOV-2023.rtf.zip)

![Screen Shot 2023-11-29 at 18 01 54](https://github.com/Mark2Mark/script-deck-plugin/assets/5973399/cce58abc-7900-4c3a-abd0-41c52edeb753)

**Comment by Mark2Mark** [comment]
Thank you! Will see what I can do.
